### ISSUE TITLE
migrate to electron

### ISSUE THREAD

**Issue by getneil** [pkgxdev/ossapp#186]
Todos:
- [x] create electron workspace
- [x] make pipeline build in CI
- [x] cp gui svelte code to electron/*: mock integration only
- [ ] convert tauri integration and http req into electron-implementation
- [ ] make pipeline build in CD
- [ ] cleanup: rm tauri build in CD

**Comment by waldyrious** [comment]
Out of curiosity, what motivated this migration?

**Comment by getneil** [comment]
> Out of curiosity, what motivated this migration?

We needed to implement a deeplinking feature, tauri does not support deeplinking effectively.

**Comment by waldyrious** [comment]
Thanks, that's good to know!
