### ISSUE TITLE
StableDiffusion Image Generation is Broken

### ISSUE THREAD

**Issue by tsmitty11** [pkgxdev/ossapp#867]
Image generation for pkgx.dev & OSSAPP has been broken since ~Feb 21, and new packages are populating without AI images. The #ai-approvals channel in Slack has also stopped serving new images.

@getneil any insight as to what might be causing this?

CC @mxcl

**Comment by mxcl** [comment]
I’ve never seen Neil respond to a ping on GitHub so good luck

**Comment by mxcl** [comment]
Doesn't matter now
